# Generated by Django 3.2.6 on 2021-08-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='doDone',
            field=models.BooleanField(default=False),
        ),
    ]


# db를 삭제하고 싶으면 마이그레이션 파일 삭제 후, 터미널에서 새롭게 마이그레이션
# python manage.py migraions